import{i as a,S as u}from"./assets/vendor-5b791d57.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const i of e.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function r(t){if(t.ep)return;t.ep=!0;const e=s(t);fetch(t.href,e)}})();const m=document.querySelector(".form"),l=document.querySelector(".gallery"),p=document.querySelector("div"),d=document.querySelector("input"),f=()=>{const o=document.createElement("span");o.classList.add("loader"),p.append(o)},c=()=>{const o=document.querySelector(".loader");o&&o.remove()};m.addEventListener("submit",o=>{f(),l.innerHTML="",o.preventDefault();const n=d.value.trim();n!==""?y(n):(a.error({message:"Please enter a search term.",position:"center",transitionIn:"fadeInLeft"}),c())});const h=new u(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250});function y(o){const s=`https://pixabay.com/api/?key=41764579-b97d65b31c0abd4efd9d4830e&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`;fetch(s).then(r=>{if(r.ok)return r.json();throw new Error(r.status)}).then(r=>{if(r.hits.length===0)a.error({message:"Sorry, there are no images matching <br>your search query. Please try again!</br>",position:"center",transitionIn:"fadeInLeft"}),c();else{const t=r.hits.map(e=>`
            <li class="gallery-item"><a href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
          <p><b>Likes: </b>${e.likes}</p>
          <p><b>Views: </b>${e.views}</p>
          <p><b>Comments: </b>${e.comments}</p>
          <p><b>Downloads: </b>${e.downloads}</p>
          </li>`).join("");l.insertAdjacentHTML("beforeend",t),h.on("show.simplelightbox").refresh(),c()}}).catch(r=>console.log(r))}
//# sourceMappingURL=commonHelpers.js.map
